---
#apache playbook
apache_listen_port: 80
apache_remove_default_vhost: true
apache_vhosts:
 - servername: "dev"
   documentroot: "/var/www/webapp"

# php playbook
php_packages: [libapache2-mod-php5]

# telegraf playbook
telegraf_plugins_extra:
    - plugin: apache

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://{{ groups['metrics'][0] }}:8086"]
      - database = "telegraf"
